id: P002970
initial_creation_type: ocr
source_metadata:
  id: bdr:W8LS20305
  title: སྐྱེ་དངོས་སྲུང་སྐྱོབ་གི་རྒྱུན་ཤེས་ཀློག་དེབ།
  author: ''
  volumes:
    0377ad1e9e144d62b22a9827640a9878:
      image_group_id: I8LS20307
      title: ''
      volume_number: 1
      total_pages: 85
