id: P002970
initial_creation_type: ocr
created_at: 22/03/2020
last_modified_at: 24/11/2021
source_metadata:
  id: bdr:W8LS20305
  title: སྐྱེ་དངོས་སྲུང་སྐྱོབ་གི་རྒྱུན་ཤེས་ཀློག་དེབ།
  author: ''
  volumes:
    0377ad1e9e144d62b22a9827640a9878:
      image_group_id: I8LS20307
      title: ''
      volume_number: 1
      total_pages: 85
      base_file: v001.txt
